baseURL = 'https://profschimd.github.io/hugo-test'
languageCode = 'en-us'
title = 'Michele Schimd'
theme = 'skihugo'
[params]
  author = 'Michele Schimd'
  description = 'Materiale di studio e di esercizio per gli alunni dello Zuccante.'
[params.social]
    mail = 'ms@m.m'
    github = 'ProfSchimd'
    linkedin = 'michele-schimd-44a85160'
    stackoverflow = '18081937'

[markup]
  [markup.goldmark.renderer]
    unsafe=true
  [markup.highlight]
    noClasses=true
[menu]
[[menu.main]]
  identifier = 'content'
  name = 'Content'
  description = 'Content of the site'
  url = '/content/'
  weight = -90
[[menu.main]]
  identifier = 'content_sr'
  name = 'SR'
  parent = 'content'
  url = '/sr/'
  weight = 1
[[menu.main]]
  identifier = 'classes'
  name = 'Classes'
  description = 'List of classes'
  url = '/classes/'
  weight = -70
[[menu.main]]
  identifier = 'about'
  name = 'About'
  description = 'About this site'
  url = '/about/'
  weight = -50

